# Write a program to generate a Fibonacci series of numbers.
# Starting numbers are 0 and 1,  new number in the series is generated by adding previous two numbers in the series.
# Example : 0, 1, 1, 2, 3, 5, 8,13,21,.....
#   a) Number of elements printed in the series should be N numbers, Where N is any +ve integer.
#   b) Generate the series until the element in the series is less than Max number.


# a) Printing the fibonacci series upto Nth term
n = int(input("Enter any number to generate Fibonacci series: "))
fst = 0
sec = 1
nxt = 0
lst1 = []

lst1.append(fst)
lst1.append(sec)

for i in range(0, n):
    nxt = fst + sec
    lst1.append(nxt)
    fst = sec
    sec = nxt
    
print("Fibonacci series upto % d " % n)
print(lst1)


# Generate the series until the element in the series is less than Max number.
fst = 0
sec = 1
max_number = int(input("Enter the Max number: "))
nxt = 0
lst2 = []

lst2.append(fst)
lst2.append(sec)

while nxt < max_number:
        nxt = fst + sec
        if nxt > max_number:
            break
        else:
            lst2.append(nxt)
        fst = sec
        sec = nxt

print("Fibonacci series upto Max number:  %  d" % max_number)
print(lst2)




